language: python
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: sambvfx
  password:
    secure: MN21sAzT+10RNXM8f1GSJ8GNBZpC5NLI86q1R55BF/HO5CkvdfTcsWUvb7FxaVEqBmdvMXe7OnPQRxvN2eyAx5j0P6oHe8eHxikSva+TdzmxTUshUSLJmpuVZvRqIqje2AzeX/ypUPZoMmI0dkC61KMR/XGs48nDVSlNYz4YFWRsjAG/jofmkqGPlKDsl9lyaYg5yNbAvlZDtSXSQkPP+LPKv8P57B4tk97fDnLLroEeslhrE3L+fL1OVl3Iiq3UGmT7q4IeQ394F0y85ztbjbpRAHAp1c05mJwlivp3gKmXSoh8sABtUCevWzV25DD8yyBI4MpDUK9kesXeVFxmjUUYYovVbW/I4QXpR9NchZa/Dh+X2a811H4s7hEHC9Ai955nhyPVbL7EmKxpWNdXTzPz/Z2+8JiT2Gwd6puO28OVvxRODDEV9JDM5Mi3xz//yjBEtQjnb4s2HGRu6n+Z3OInqNYzJA1u6/fAdeKv/KEyI3XcyMph9D90rgKtCaaDxI1fQ+kVab7jWz+3dR4dibBRo3LCHbMr21fjgCey6ico7u1CrabGlJXaWdpkUVSKfmsCLGEgfybyKDOEYHAU8pBePnrZNikKpHyAklsjonzkbfUbWBFekvcY4+jQz48e0P+4BYnl6GbktIzgCFi7yDzfr1f5U/kpPzyxAdaMks4=
  on:
    tags: true
    python: 2.7
